# Generated by Django 5.2.1 on 2025-05-22 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone1', models.CharField(max_length=25, verbose_name='Телефон 1')),
                ('phone2', models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон 2')),
            ],
            options={
                'verbose_name': 'Изделия',
                'verbose_name_plural': 'Изделия',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='contact_photos/', verbose_name='Фото')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание фото')),
                ('contact_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='webapp.itemobject', verbose_name='Объект изделия')),
            ],
            options={
                'verbose_name': 'Фото изделия',
                'verbose_name_plural': 'Фото изделия',
            },
        ),
    ]
