# Generated by Django 5.2.1 on 2025-05-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('phone1', models.CharField(blank=True, max_length=20, verbose_name='Телефон 1')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='Телефон 2')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Фото 1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Фото 2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Фото 3')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Фото 4')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
