# Generated by Django 5.2.1 on 2025-05-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='photo1_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание фото 1'),
        ),
        migrations.AddField(
            model_name='banner',
            name='photo2_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание фото 2'),
        ),
        migrations.AddField(
            model_name='banner',
            name='photo3_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание фото 3'),
        ),
        migrations.AddField(
            model_name='banner',
            name='photo4_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание фото 4'),
        ),
    ]
