# Generated by Django 5.2.1 on 2025-05-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_banner_photo1_description_banner_photo2_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemobject',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
