# Generated by Django 5.2.1 on 2025-05-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_itemobject_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HadContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Шапка - 📞 Телефон и 📧 Почта',
                'verbose_name_plural': 'Шапка - 📞 Телефон и 📧 Почта',
            },
        ),
    ]
