# Generated by Django 5.2.1 on 2025-05-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_hadcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('phone_one', models.CharField(max_length=20, verbose_name='Телефон1')),
                ('phone_two', models.CharField(max_length=20, verbose_name='Телефон2')),
            ],
            options={
                'verbose_name': 'Услуги 👷🏻\u200d♂️ в Болке Формы - 📞 Телефоны',
                'verbose_name_plural': 'Услуги 👷🏻\u200d♂️ в Болке Формы - 📞 Телефоны',
            },
        ),
    ]
