# Generated by Django 5.2.1 on 2025-05-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_servicescontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone_one', models.CharField(max_length=20, verbose_name='Телефон 1')),
                ('phone_two', models.CharField(max_length=20, verbose_name='Телефон 2')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('vk', models.URLField(blank=True, verbose_name='ВКонтакте')),
            ],
            options={
                'verbose_name': 'Информация футера',
                'verbose_name_plural': 'Информация футера',
            },
        ),
    ]
