# Generated by Django 5.2.1 on 2025-05-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_footerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerinfo',
            name='email',
            field=models.EmailField(default='aironmaster@tut.by', max_length=254, verbose_name='Почта'),
        ),
    ]
