# Generated by Django 5.2.1 on 2025-05-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_footerinfo_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='about_photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'ℹ️ О компании',
                'verbose_name_plural': 'ℹ️ О компании',
            },
        ),
        migrations.AlterModelOptions(
            name='footerinfo',
            options={'verbose_name': '🚧 Информация футера', 'verbose_name_plural': '🚧 Информация футера'},
        ),
    ]
