# Generated by Django 5.2.1 on 2025-05-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_ourservice_itemobject_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservice',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
