# Generated by Django 5.2.1 on 2025-05-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_ourservice_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '🌄 Баннер', 'verbose_name_plural': '🌄 Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='itemobject',
            options={'ordering': ['name'], 'verbose_name': '🎷 Изделия', 'verbose_name_plural': '🎷 Изделия'},
        ),
        migrations.AlterModelOptions(
            name='itemphoto',
            options={'verbose_name': '🖼️ Фото изделия', 'verbose_name_plural': '🖼️ Фото изделия'},
        ),
        migrations.AlterModelOptions(
            name='ourservice',
            options={'ordering': ['name'], 'verbose_name': '🛠️ Наш сервис', 'verbose_name_plural': '🛠️ Наши сервисы'},
        ),
    ]
