# Generated by Django 5.2.1 on 2025-05-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_banner_options_alter_itemobject_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='finished_products/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '✅ Готовая продукция',
                'verbose_name_plural': '✅ Готовая продукция',
                'ordering': ['name'],
            },
        ),
    ]
