# Generated by Django 5.2.1 on 2025-05-29 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_finishedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerinfo',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='footerinfo',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='footerinfo',
            name='vk',
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='phone_two',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон 2'),
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название соцсети')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='Иконка')),
                ('footer_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='webapp.footerinfo', verbose_name='Футер')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
