# Generated by Django 5.2.1 on 2025-05-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_remove_footerinfo_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemobject',
            name='is_decor_elements',
            field=models.BooleanField(default=False, verbose_name='Элементы декора'),
        ),
        migrations.AddField(
            model_name='itemobject',
            name='is_grills',
            field=models.BooleanField(default=False, verbose_name='Мангалы'),
        ),
        migrations.AddField(
            model_name='itemobject',
            name='is_metal_structures',
            field=models.BooleanField(default=False, verbose_name='Металлоконструкции'),
        ),
        migrations.AddField(
            model_name='itemobject',
            name='is_steps_and_stairs',
            field=models.BooleanField(default=False, verbose_name='Ступеньки и Лестницы'),
        ),
    ]
