# Generated by Django 5.2.1 on 2025-05-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_itemobject_is_decor_elements_itemobject_is_grills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Баннер страницы',
                'verbose_name_plural': 'Баннеры страниц',
                'ordering': ['name'],
            },
        ),
    ]
