# Generated by Django 5.2.1 on 2025-05-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_bannerpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerpage',
            options={'ordering': ['name'], 'verbose_name': '⛵ Баннер страницы', 'verbose_name_plural': '⛵ Баннеры страниц'},
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='category',
            field=models.CharField(blank=True, choices=[('metal_structures', 'Металлоконструкции'), ('steps_and_stairs', 'Ступеньки и Лестницы'), ('grills', 'Мангалы'), ('decor_elements', 'Элементы декора')], max_length=50, null=True, unique=True, verbose_name='Категория'),
        ),
    ]
