# Generated by Django 5.2.1 on 2025-05-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_alter_bannerpage_options_bannerpage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemobject',
            name='description_more',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
