# Generated by Django 5.2.1 on 2025-07-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_servicephoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinishedProduct',
        ),
    ]
