# Generated by Django 5.2.1 on 2025-07-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_delete_finishedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemobject',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='На главную'),
        ),
        migrations.AlterField(
            model_name='bannerpage',
            name='category',
            field=models.CharField(choices=[('metal_structures', 'Металлоконструкции'), ('procladki', 'Прокладки'), ('steps_and_stairs', 'Ступеньки и Лестницы'), ('grills', 'Мангалы'), ('decor_elements', 'Элементы декора')], max_length=50, null=True, unique=True, verbose_name='Категория'),
        ),
    ]
