# Generated by Django 5.2.1 on 2025-08-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_itemobject_is_main_alter_bannerpage_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('news_text', models.TextField(verbose_name='Основной текст новости')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('photo', models.ImageField(upload_to='news_photos/', verbose_name='Фото новости')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главная новость')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date'],
            },
        ),
    ]
