# Generated by Django 5.2.1 on 2025-08-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='photo1_link',
            field=models.URLField(blank=True, verbose_name='Ссылка для фото 1'),
        ),
        migrations.AddField(
            model_name='banner',
            name='photo2_link',
            field=models.URLField(blank=True, verbose_name='Ссылка для фото 2'),
        ),
        migrations.AddField(
            model_name='banner',
            name='photo3_link',
            field=models.URLField(blank=True, verbose_name='Ссылка для фото 3'),
        ),
        migrations.AddField(
            model_name='banner',
            name='photo4_link',
            field=models.URLField(blank=True, verbose_name='Ссылка для фото 4'),
        ),
    ]
