# Generated by Django 5.2.1 on 2025-08-06 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_banner_photo1_link_banner_photo2_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservice',
            name='technology',
            field=models.TextField(blank=True, verbose_name='Технология гибки металла'),
        ),
        migrations.CreateModel(
            name='ServiceAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='service_advantages_icons/', verbose_name='Иконка преимущества')),
                ('text', models.CharField(max_length=255, verbose_name='Текст преимущества')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='webapp.ourservice')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Толщина металла, мм')),
                ('cost', models.CharField(max_length=50, verbose_name='Стоимость 1 гиба (текст)')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='webapp.ourservice')),
            ],
            options={
                'verbose_name': 'Стоимость услуги',
                'verbose_name_plural': 'Стоимость услуг',
                'ordering': ['thickness'],
            },
        ),
    ]
