# Generated by Django 5.2.1 on 2025-08-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_ourservice_technology_serviceadvantage_serviceprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceadvantage',
            name='icon',
            field=models.FileField(upload_to='service_advantages_icons/', verbose_name='Иконка преимущества'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='cost',
            field=models.CharField(max_length=50, verbose_name='Стоимость'),
        ),
    ]
