# Generated by Django 5.2.1 on 2025-08-06 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_alter_serviceadvantage_icon_alter_serviceprice_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='service_videos/', verbose_name='Видео')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название видео')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='webapp.ourservice')),
            ],
        ),
    ]
