# Generated by Django 5.2.1 on 2025-08-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_servicevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemobject',
            name='mission',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Предназначение'),
        ),
    ]
