# Generated by Django 5.2.1 on 2025-08-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_itemobject_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemobject',
            name='is_promotions',
            field=models.BooleanField(default=False, verbose_name='В акцию'),
        ),
        migrations.AddField(
            model_name='itemobject',
            name='is_stok',
            field=models.BooleanField(default=False, verbose_name='На складе'),
        ),
    ]
