# Generated by Django 5.2.1 on 2025-08-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_itemobject_is_promotions_itemobject_is_stok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='Фото')),
                ('advantages', models.TextField(blank=True, help_text='Опишите основные преимущества', verbose_name='Преимущества')),
                ('additional_description', models.TextField(blank=True, verbose_name='Дополнительное описание')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
            },
        ),
    ]
