# Generated by Django 5.2.1 on 2025-08-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='service_videos/', verbose_name='Видео'),
        ),
    ]
