# Generated by Django 5.2.1 on 2025-08-10 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_advertisement_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Реклама', 'verbose_name_plural': 'Реклама'},
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='video',
        ),
        migrations.CreateModel(
            name='AdvertisementVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название видео')),
                ('video', models.FileField(upload_to='service_videos/', verbose_name='Видео')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='webapp.advertisement')),
            ],
        ),
    ]
