# Generated by Django 5.2.1 on 2025-09-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='our_works/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Наши работы',
                'verbose_name_plural': 'Наша работа',
            },
        ),
    ]
