# Generated by Django 5.2.1 on 2025-09-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_ourworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourworks',
            name='characteristics',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='Характеристики'),
        ),
    ]
