# Generated by Django 5.2.1 on 2025-10-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_ourworks_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpage',
            name='category',
            field=models.CharField(choices=[('metal_structures', 'Металлоконструкции'), ('procladki', 'Прокладки'), ('steps_and_stairs', 'Ступеньки и Лестницы'), ('grills', 'Мангалы'), ('decor_elements', 'Элементы декора')], max_length=50, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='technology',
            field=models.TextField(blank=True, verbose_name='Технология'),
        ),
    ]
