# Generated by Django 5.2.1 on 2025-10-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_alter_bannerpage_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprice',
            options={'ordering': ['metal_type', 'thickness'], 'verbose_name': 'Стоимость услуги', 'verbose_name_plural': 'Стоимость услуг'},
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='metal_type',
            field=models.CharField(default='Сталь', max_length=100, verbose_name='Тип металла'),
        ),
    ]
