# Generated by Django 5.2.1 on 2025-10-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_alter_serviceprice_options_serviceprice_metal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedMetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hазвание металла')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='metal_photos/', verbose_name='Фото металла')),
            ],
            options={
                'verbose_name': 'Обрабатываемый металл',
                'verbose_name_plural': 'Обрабатываемые металлы',
            },
        ),
    ]
