# Generated by Django 5.2.1 on 2025-11-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_metalworkingservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='category_icons/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Сайт Бар Категории',
                'verbose_name_plural': 'Сайт Бар Категории',
            },
        ),
        migrations.AlterModelOptions(
            name='metalworkingservice',
            options={'verbose_name': 'Блок металлообработка', 'verbose_name_plural': 'Блок металлообработка'},
        ),
    ]
