# Generated by Django 5.2.1 on 2025-11-13 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_sitebarcategory_alter_metalworkingservice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprice',
            name='metal_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviceprice_metal_type_new', to='webapp.processedmetal', verbose_name='Новый тип металла (ForeignKey)'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость BYN (без НДС)'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='metal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviceprice_metal_type', to='webapp.processedmetal', verbose_name='Тип металла'),
        ),
    ]
