# Generated by Django 5.2.1 on 2025-11-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_serviceprice_metal_type_new_alter_serviceprice_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprice',
            name='metal_type_new',
        ),
    ]
