# Generated by Django 5.2.1 on 2025-11-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0041_remove_serviceprice_metal_type_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprice',
            name='metal_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviceprice_metal_type_new', to='webapp.processedmetal', verbose_name='Новый тип металла (ForeignKey)'),
        ),
    ]
