# Generated by Django 5.2.1 on 2025-11-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0042_serviceprice_metal_type_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprice',
            name='metal_type_new',
        ),
    ]
