# Generated by Django 5.2.1 on 2025-11-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0043_remove_serviceprice_metal_type_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeDConstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('descriptions', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '3D Моделирование (описание)',
                'verbose_name_plural': '3D Моделирование (описание)',
            },
        ),
    ]
