# Generated by Django 5.2.1 on 2025-11-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0044_threedconstructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='services_for/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Блок Для',
                'verbose_name_plural': 'Блок Для',
            },
        ),
    ]
