# Generated by Django 5.2.1 on 2025-11-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0045_adventureservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureservice',
            name='category',
            field=models.CharField(blank=True, choices=[('metal_structures', 'Металлоконструкции'), ('procladki', 'Прокладки'), ('steps_and_stairs', 'Ступеньки и Лестницы'), ('grills', 'Мангалы'), ('decor_elements', 'Элементы декора')], max_length=50),
        ),
    ]
