# Generated by Django 5.2.1 on 2026-04-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0046_adventureservice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemobject',
            name='is_main_top',
            field=models.BooleanField(default=False, verbose_name='На главную (в верх)'),
        ),
    ]
